services:
  web:
    build: .
    command: >
      bash -c "/wait-for-it.sh db:5432 --timeout=60 -- 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:9100"
    volumes:
      - .:/code
    ports:
      - "9100:9100"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - ELASTICSEARCH_DSL_HOSTS=http://es:9200

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  postgres_data:
