# Generated by Django 5.1.7 on 2025-04-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarddoc',
            name='contents_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standarddoc',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
